### ISSUE TITLE
Support for custom transport layers

### ISSUE THREAD

**Issue by JustTalDevelops** [Sandertv/gophertunnel#133]
There is currently a way to listen or dial on a specific network - however, it is fairly limiting with no proper way to register custom transport layers and is non-functional with anything that isn't RakNet.

**Comment by Sandertv** [comment]
I propose we combine https://pkg.go.dev/image#RegisterFormat and the `network` parameter in `Listen` and `Dial` (https://github.com/Sandertv/gophertunnel/blob/master/minecraft/listener.go#L85). We could have a `minecraft.RegisterNetwork` function, something like this:
```go
type Network interface {
  ReadPacket(...) ...
  WritePacket(...) ...
  Latency(...) ...
}

func RegisterNetwork(name string, n Network) { ... }
```
to register new networks so that this parameter actually becomes useful.
