### ISSUE TITLE
Client crashes when joining a BDS server with the new camera features

### ISSUE THREAD

**Issue by IvanCraft623** [Sandertv/gophertunnel#188]
This happens specifically when gophertunnel retransmits the CameraPresets packet

**Comment by IvanCraft623** [comment]
There is a world with new cameras enabled [here](https://cdn.discordapp.com/attachments/637335508166377513/1116390161429843998/PMTests.zip).

Although I already reported this on discord it is better to open an issue here.

**Comment by JavierLeon9966** [comment]
The issue here is that the camera's experiment isn't in the `ResourcePackStack` packet experiments field. To workaround this you would  need to override this https://github.com/Sandertv/gophertunnel/blob/a4bc2f93fb3d2fe77c684368f8fb7e9857ee2772/minecraft/conn.go#L979 with:
```go
pk := &packet.ResourcePackStack{BaseGameVersion: protocol.CurrentVersion, Experiments: []protocol.ExperimentData{{Name: "cameras", Enabled: true}}}
```
Perhaps gophertunnel can somehow get the `GameData` before reaching that stage so this can be fixed permanently.
