### ISSUE TITLE
Freezes when multiple clients try to join

### ISSUE THREAD

**Issue by crqyder** [Sandertv/gophertunnel#223]

**Comment by MajesticPaws** [comment]
The gophertunnel code for spawning the clients to reproduce this behavior can be found on this gist: https://gist.github.com/MajesticPaws/8348f328c81eb626480eb555ccce453d

**Comment by MajesticPaws** [comment]
The video showing the freezing issue is right here: 

https://github.com/Sandertv/gophertunnel/assets/165836361/131da945-7c57-4cf3-b1bf-fb849d981e86

**Comment by MajesticPaws** [comment]
Upon debugging the code there are two problems I can find. One is the calling of `s.initPlayerList()` being blocking to due to `sessionMu` being locked and second of all the `srv.incoming` channel is also locked due to too many values being inserted in it asynchronously. It is due to the fact that channels also use some sort of synchronisation primitive inside them which is abstracted away.
